var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/home/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03eew7j._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_056mif5.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-3yg4k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__034ycl1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_home_page_actions_0963r4p.js")
R.m(31099)
module.exports=R.m(31099).exports
