var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/reviews/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g98.kd._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~_z.-e.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-3yg4k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__034ycl1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_0qalhup._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_reviews_page_actions_0-74.w_.js")
R.m(61315)
module.exports=R.m(61315).exports
