var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/users/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0eyd4y0._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_nhnht.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-3yg4k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/_00ic4j6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_0qalhup._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_users_page_actions_0vljt68.js")
R.m(72410)
module.exports=R.m(72410).exports
